spring:
#  datasource:
#    url: jdbc:mysql://
#    username:
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  security:
    oauth2:
      registration:
        google:
          clientId:
          client-secret:
        facebook:
          clientId:
          client-secret:

custom:
  oauth2:
    kakao:
      client-id: